services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
      KC_FEATURES: import-export
      KC_METRICS_ENABLED: "true"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro