services:
  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.1
    command:
      - start-dev
      - --import-realm
      - --log-level=DEBUG
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_FEATURES: import-export
      KC_METRICS_ENABLED: "true"
    ports:
      - 8080:8080
    depends_on:
      postgres-keycloak:
       condition: service_healthy
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

volumes:
  postgres_keycloak_data: